# Generated by Django 4.2.16 on 2025-03-06 16:25

import apps.products.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='品牌名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='品牌描述')),
                ('logo_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='品牌LOGO')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '品牌',
                'verbose_name_plural': '品牌列表',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=100, verbose_name='英文名称')),
                ('name', models.CharField(max_length=100, verbose_name='中文名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('rank', models.IntegerField(default=0, verbose_name='排序')),
                ('level', models.IntegerField(choices=[(1, '一级分类'), (2, '二级分类'), (3, '三级分类'), (4, '四级分类'), (5, '五级分类'), (6, '六级分类'), (7, '七级分类')], default=1, verbose_name='分类层级')),
                ('is_last_level', models.BooleanField(default=False, verbose_name='是否最后一级')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='products.category', verbose_name='父类别')),
            ],
            options={
                'verbose_name': '商品分类',
                'verbose_name_plural': '商品分类',
                'ordering': ['rank', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SPU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='SPU编码')),
                ('name', models.CharField(max_length=100, verbose_name='SPU名称')),
                ('product_type', models.CharField(choices=[('math_design', '设计款'), ('ready_made', '现货款'), ('raw_material', '材料'), ('packing_material', '包材')], max_length=20, verbose_name='产品类型')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('sales_channel', models.CharField(blank=True, max_length=20, null=True, verbose_name='销售渠道')),
                ('design_elements', models.CharField(blank=True, help_text='设计元素，如：蝴蝶', max_length=20, null=True, verbose_name='设计元素')),
                ('production_process', models.CharField(blank=True, choices=[('metal', '金属类'), ('resin', '树脂类'), ('plush', '毛绒类'), ('plastic', '塑料类')], help_text='主要生产工艺', max_length=20, null=True, verbose_name='生产工艺')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.brand', verbose_name='品牌')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.category', verbose_name='商品分类')),
                ('poc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='产品专员')),
            ],
            options={
                'verbose_name': 'SPU',
                'verbose_name_plural': 'SPU列表',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='SKU编码')),
                ('name', models.CharField(max_length=100, verbose_name='SKU名称')),
                ('material', models.CharField(max_length=50, verbose_name='材质')),
                ('color', models.CharField(max_length=50, verbose_name='颜色')),
                ('plating_process', models.CharField(choices=[('none', '无电镀'), ('18k_gold', '18K金'), ('18k_silver', '18K银')], default='none', max_length=20, verbose_name='电镀工艺')),
                ('surface_treatment', models.CharField(blank=True, max_length=100, null=True, verbose_name='表面处理')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='重量(g)')),
                ('length', models.IntegerField(blank=True, null=True, verbose_name='长(mm)')),
                ('width', models.IntegerField(blank=True, null=True, verbose_name='宽(mm)')),
                ('height', models.IntegerField(blank=True, null=True, verbose_name='高(mm)')),
                ('other_dimensions', models.CharField(blank=True, max_length=25, null=True, verbose_name='其他尺寸')),
                ('suppliers_list', models.TextField(blank=True, default='[]', verbose_name='供应商列表')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to=apps.products.models.product_image_path, verbose_name='主图')),
                ('images', models.JSONField(blank=True, default=list, help_text='存储多张图片的URL列表', verbose_name='图片列表')),
                ('is_reviewed', models.BooleanField(default=False, verbose_name='是否已审核')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('spu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.spu', verbose_name='所属SPU')),
            ],
            options={
                'verbose_name': 'SKU',
                'verbose_name_plural': 'SKU列表',
                'ordering': ['-created_at'],
            },
        ),
    ]
