# Generated by Django 4.2.16 on 2025-03-16 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='other_dimensions',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='其他尺寸'),
        ),
    ]
