# Generated by Django 4.2.16 on 2025-03-07 09:29

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='类目编码')),
                ('name', models.CharField(max_length=50, verbose_name='类目名称')),
                ('category_type', models.CharField(choices=[('resin', '树脂类'), ('metal', '金属类'), ('ceramic', '陶瓷类'), ('plush', '毛绒类')], max_length=20, verbose_name='类目类型')),
                ('description', models.TextField(blank=True, verbose_name='类目描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '生产类目',
                'verbose_name_plural': '生产类目',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ProductionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='任务编号')),
                ('order_type', models.CharField(choices=[('trial', '试产'), ('mass', '量产')], max_length=10, verbose_name='生产类型')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='计划数量')),
                ('priority', models.IntegerField(choices=[(0, '紧急'), (1, '高'), (2, '中'), (3, '低')], default=2, verbose_name='优先级')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('in_progress', '进行中'), ('completed', '已完成'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态')),
                ('planned_start_date', models.DateField(verbose_name='计划开始日期')),
                ('planned_end_date', models.DateField(verbose_name='计划结束日期')),
                ('actual_start_date', models.DateField(blank=True, null=True, verbose_name='实际开始日期')),
                ('actual_end_date', models.DateField(blank=True, null=True, verbose_name='实际结束日期')),
                ('description', models.TextField(blank=True, verbose_name='任务描述')),
                ('technical_requirements', models.TextField(blank=True, verbose_name='技术要求')),
                ('quality_requirements', models.TextField(blank=True, verbose_name='质量要求')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='production.productioncategory', verbose_name='生产类目')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_orders', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='managed_orders', to=settings.AUTH_USER_MODEL, verbose_name='生产主管')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_orders', to='products.product', verbose_name='产品')),
            ],
            options={
                'verbose_name': '生产任务',
                'verbose_name_plural': '生产任务',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductionStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_type', models.CharField(choices=[('3d_modeling', '3D建模'), ('model_printing', '模型打印'), ('casting', '铸造'), ('plating', '电镀'), ('post_processing', '后处理')], max_length=20, verbose_name='步骤类型')),
                ('name', models.CharField(help_text='可以是预定义步骤，也可以是自定义步骤名称', max_length=100, verbose_name='步骤名称')),
                ('sequence', models.IntegerField(verbose_name='步骤顺序')),
                ('description', models.TextField(blank=True, verbose_name='步骤描述')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('in_progress', '进行中'), ('completed', '已完成'), ('on_hold', '已暂停')], default='pending', max_length=20, verbose_name='状态')),
                ('planned_duration', models.DurationField(verbose_name='计划耗时')),
                ('actual_duration', models.DurationField(blank=True, null=True, verbose_name='实际耗时')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('quality_check_result', models.TextField(blank=True, verbose_name='质检结果')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('attachments', models.JSONField(blank=True, default=list, help_text='步骤相关的文件URL列表，如3D文件、图纸等', verbose_name='附件列表')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operated_steps', to=settings.AUTH_USER_MODEL, verbose_name='操作员')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='production.productionorder', verbose_name='生产任务')),
            ],
            options={
                'verbose_name': '生产步骤',
                'verbose_name_plural': '生产步骤',
                'ordering': ['order', 'sequence'],
                'unique_together': {('order', 'sequence')},
            },
        ),
        migrations.CreateModel(
            name='ProductionComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_type', models.CharField(choices=[('general', '普通评论'), ('issue', '问题报告'), ('solution', '解决方案')], default='general', max_length=20, verbose_name='评论类型')),
                ('content', models.TextField(verbose_name='评论内容')),
                ('images', models.JSONField(blank=True, default=list, help_text='评论相关的图片URL列表', verbose_name='图片列表')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_comments', to=settings.AUTH_USER_MODEL, verbose_name='评论人')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='production.productionorder', verbose_name='生产任务')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='production.productioncomment', verbose_name='父评论')),
                ('step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='production.productionstep', verbose_name='生产步骤')),
            ],
            options={
                'verbose_name': '生产评论',
                'verbose_name_plural': '生产评论',
                'ordering': ['created_at'],
            },
        ),
    ]
