# Generated by Django 4.2.16 on 2025-03-07 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_alter_productionorder_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productionorder',
            options={'ordering': ['priority_order', '-created_at'], 'verbose_name': '生产任务', 'verbose_name_plural': '生产任务'},
        ),
        migrations.AddField(
            model_name='productionorder',
            name='priority_order',
            field=models.IntegerField(default=0, help_text='数字越小优先级越高', verbose_name='优先级排序'),
        ),
    ]
