# Generated by Django 4.2.16 on 2025-03-07 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0003_alter_productionorder_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionorder',
            name='attachments',
            field=models.JSONField(blank=True, default=list, help_text='任务相关的文件URL列表，如设计文件、参考图等', verbose_name='附件列表'),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='main_image',
            field=models.ImageField(blank=True, help_text='任务相关的主要图片', null=True, upload_to='production/orders/%Y/%m', verbose_name='主图'),
        ),
    ]
