# Generated by Django 4.2.16 on 2025-03-07 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0004_productionorder_attachments_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='渠道编码')),
                ('name', models.CharField(max_length=50, verbose_name='渠道名称')),
                ('description', models.TextField(blank=True, verbose_name='渠道描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '来源渠道',
                'verbose_name_plural': '来源渠道',
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='productionorder',
            name='channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='production.productionchannel', verbose_name='来源渠道'),
        ),
    ]
