# Generated by Django 4.2.16 on 2025-03-27 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogisticsStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('unshipped', '未发货'), ('InfoReceived', '已接收信息'), ('PickedUp', '已揽收'), ('Departure', '已发出'), ('Arrival', '已到达'), ('AvailableForPickup', '可提货'), ('OutForDelivery', '派送中'), ('Delivered', '已签收'), ('Returning', '退回中'), ('Returned', '已退回')], max_length=20, unique=True, verbose_name='状态代码')),
                ('name', models.CharField(max_length=50, verbose_name='状态名称')),
                ('description', models.TextField(blank=True, verbose_name='状态描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '物流状态',
                'verbose_name_plural': '物流状态',
                'db_table': 'logistics_status',
                'ordering': ['code'],
            },
        ),
        migrations.RemoveField(
            model_name='package',
            name='pkg_status_code',
        ),
        migrations.AddField(
            model_name='package',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='packages', to='logistics.logisticsstatus', verbose_name='包裹状态'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tracking',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tracking_records', to='logistics.logisticsstatus', verbose_name='物流状态'),
        ),
    ]
